services:
  postgres:
    image: postgres:16
    container_name: orgchat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: UTC
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    # فقط در DEV باز باشد؛ در PROD حذف کن
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orgchat-backend
    restart: unless-stopped
    environment:
      DJANGO_SECRET: ${DJANGO_SECRET}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      TZ: UTC
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    command: >
      bash -lc "
        python -V &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

  # اختیاری
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: orgchat-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:80"

volumes:
  pgdata:
